apiVersion: apps/v1
kind: Deployment
metadata:
  name: spof-tp
  namespace: kraken
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spoftp
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: spoftp
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: lst
                operator: In
                values:
                - yyyyy
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - spoftp
            topologyKey: kubernetes.io/hostname
      containers:
      - name: spoftp
        image: ubuntu
        command: ["/bin/bash", "-ce", "tail -f /dev/null"]
        volumeMounts:
        - name: datablk
          mountPath: /mnt/data
      volumes:
      - name: datablk
        persistentVolumeClaim:
          claimName: spofpvc
